apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: nodeport
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ksql-cli
  name: ksql-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ksql-cli
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: nodeport
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ksql-cli
    spec:
      containers:
        - command:
            - /bin/sh
          image: confluentinc/cp-ksql-cli:5.4.1
          name: ksql-cli
          resources: {}
          tty: true
      restartPolicy: Always
status: {}
